"""
study_set.py — Generates a Barnhaus Study Set from an open Revit model.

Study set = 9 sheets:
  A100    Cover Sheet (renderings)
  A100.1  Cover Sheet Interior
  A100.2.1  3D Views (wireframe)
  A100.2.2  3D Cuts (section box)
  A101.1  Floor Plan F1
  A101.2  Floor Plan F2 (if 2-story)
  A105    Elevations - Sides  (tags/dims hidden)
  A106    Elevations - Front/Back  (tags/dims hidden)
  A111    Upgrade upsell page (generated by Python)

Usage:
    python3 run.py study-set
"""

import os
import json
import time
from core import revit_client as rc
from core.project_state import scan_project, load_state
from tasks.study_set.a111_generator import generate_a111

# ── Categories to hide in study set elevation views ─────────────────────────
# These Revit annotation category names get visibility turned off
HIDE_CATEGORIES = [
    "Door Tags",
    "Window Tags",
    "Dimensions",
    "Detail Items",
    "Section Boxes",
    "Callout Heads",
    "Callout Boundaries",
    "Elevation Tags",
    "Level Tags",
    "Grid Heads",
    "Keynote Tags",
    "Material Tags",
    "Generic Annotation",
]

# ── Sheet numbers that belong in a study set ─────────────────────────────────
STUDY_SHEET_NUMBERS = {"A100", "A100.1", "A100.2.1", "A100.2.2", "A101.1", "A101.2", "A105", "A106"}


def run(state: dict = None):
    """Main entry point — generate the study set."""
    if state is None:
        state = load_state()

    doc_title = state.get("summary", {}).get("title", "Unknown Project")
    is_two_story = state.get("summary", {}).get("is_two_story", False)

    print(f"\n📐 Study Set Generator — {doc_title}")
    print("=" * 55)

    # Step 1: Find existing sheets and views
    print("\n── Step 1: Scanning sheets & views ──")
    sheets = _get_sheets()
    views  = _get_views()

    sheet_map = {s.get("number", s.get("sheet_number", "")): s for s in sheets}
    view_map  = {v.get("name", ""): v for v in views}

    _report_existing(sheet_map, is_two_story)

    # Step 2: Handle 3D views (A100.2.1 / A100.2.2)
    print("\n── Step 2: 3D Views ──")
    needs_3d_input = _handle_3d_views(sheet_map, view_map)

    # Step 3: Create/update study set elevation views (tags hidden)
    print("\n── Step 3: Study Set Elevation Views ──")
    study_elev_views = _create_study_elevations(view_map, sheet_map)

    # Step 4: Build study set sheet set
    print("\n── Step 4: Building Study Set Sheets ──")
    _build_study_sheets(sheet_map, view_map, study_elev_views, is_two_story)

    # Step 5: Generate A111 upsell page
    print("\n── Step 5: A111 Upsell Page ──")
    a111_path = _handle_a111(doc_title, sheet_map)

    # Step 6: Export PDF
    print("\n── Step 6: Export PDF ──")
    if needs_3d_input:
        print("⏸  Pausing before export — 3D views need positioning.")
        print("   In Revit: adjust the 3D view camera angles on sheets A100.2.1 and A100.2.2,")
        print("   then run:  python3 run.py study-set-export")
        _save_export_state(doc_title, a111_path)
    else:
        export_study_set(doc_title, a111_path)


def export_study_set(doc_title: str = None, a111_path: str = None):
    """Export the study set PDF. Can be called standalone after 3D view adjustment."""
    state = load_state()
    if doc_title is None:
        doc_title = state.get("summary", {}).get("title", "Unknown Project")
    if a111_path is None:
        a111_path = _load_export_state().get("a111_path")

    print(f"\n📤 Exporting study set — {doc_title}")
    revit_pdf_path = _export_revit_pdf(doc_title)

    if revit_pdf_path and a111_path:
        final_path = _merge_pdfs(revit_pdf_path, a111_path, doc_title)
        print(f"\n✅ Study set ready: {final_path}")
    elif revit_pdf_path:
        print(f"\n✅ Study set exported (no A111 merge): {revit_pdf_path}")
    else:
        print("\n⚠️  Revit PDF export not available via bridge — export manually:")
        print("   File → Print → Sheet Set: STUDY SET → PDF")
        if a111_path:
            print(f"   Then merge with: {a111_path}")


# ─────────────────────────────────────────────────────────────────────────────
# INTERNAL STEPS
# ─────────────────────────────────────────────────────────────────────────────

def _get_sheets() -> list:
    result = rc.call("revit.list_sheets", {})
    if result.get("success"):
        return result.get("result", {}).get("sheets", [])
    print("  ⚠️  Could not list sheets")
    return []


def _get_views() -> list:
    result = rc.call("revit.list_views", {})
    if result.get("success"):
        return result.get("result", {}).get("views", [])
    return []


def _report_existing(sheet_map: dict, is_two_story: bool):
    needed = {"A100", "A100.1", "A100.2.1", "A100.2.2", "A101.1", "A105", "A106"}
    if is_two_story:
        needed.add("A101.2")

    for num in sorted(needed):
        status = "✅" if num in sheet_map else "❌ missing"
        print(f"  {num}: {status}")


def _handle_3d_views(sheet_map: dict, view_map: dict) -> bool:
    """
    Check if 3D view sheets exist. If not, try to create them.
    Returns True if Mitch needs to manually position them.
    """
    has_3d_sheet    = "A100.2.1" in sheet_map
    has_3d_cut_sheet = "A100.2.2" in sheet_map

    if has_3d_sheet and has_3d_cut_sheet:
        print("  ✅ 3D view sheets already exist — skipping")
        return False

    print("  ⚠️  3D view sheets missing — attempting to create...")
    needs_input = False

    # Try to create wireframe 3D views
    if not has_3d_sheet:
        created = _try_create_3d_views(view_map)
        if created:
            print("  ✅ Created 3D wireframe views — you'll need to set camera angles in Revit")
            needs_input = True
        else:
            print("  ℹ️  Could not auto-create 3D views — create manually in Revit:")
            print("     View → 3D View → Camera, name it 'Study - 3D Back'")
            print("     View → 3D View → Camera, name it 'Study - 3D Side'")
            needs_input = True

    return needs_input


def _try_create_3d_views(view_map: dict) -> bool:
    """Try to create 3D perspective/wireframe views via bridge."""
    views_to_create = [
        {"name": "Study - 3D Back",   "type": "ThreeDimensional"},
        {"name": "Study - 3D Side",   "type": "ThreeDimensional"},
        {"name": "Study - 3D Side 2", "type": "ThreeDimensional"},
        {"name": "Study - 3D Cut Back",  "type": "ThreeDimensional"},
        {"name": "Study - 3D Cut Front", "type": "ThreeDimensional"},
    ]

    created_any = False
    for v in views_to_create:
        if v["name"] in view_map:
            print(f"  ✅ View '{v['name']}' already exists")
            continue
        result = rc.call("revit.create_3d_view", {
            "name": v["name"],
            "view_type": v["type"],
        })
        if result.get("success"):
            print(f"  ✅ Created view: {v['name']}")
            created_any = True
        else:
            print(f"  ⚠️  Could not create '{v['name']}': {result.get('error', 'unsupported')}")

    return created_any


def _create_study_elevations(view_map: dict, sheet_map: dict) -> dict:
    """
    Duplicate the A105/A106 elevation views and apply study set visibility
    (tags and detailed dimensions hidden).

    Returns: {sheet_number: view_id} mapping for the clean study views.
    """
    # Map sheet numbers to the view names we want to find/create
    elevation_targets = {
        "A105": {"search": ["Elev - Sides", "A105", "Elevations Sides", "ELEVATIONS SIDES"],
                 "study_name": "Study - Elevations Sides"},
        "A106": {"search": ["Elev - Front Back", "A106", "Elevations Front Back", "ELEVATIONS FRONT BACK"],
                 "study_name": "Study - Elevations Front Back"},
    }

    study_views = {}

    for sheet_num, cfg in elevation_targets.items():
        # Find source view
        source_view = _find_view(view_map, cfg["search"])
        study_name  = cfg["study_name"]

        if study_name in view_map:
            print(f"  ✅ Study view already exists: '{study_name}'")
            study_views[sheet_num] = view_map[study_name].get("id")
            continue

        if source_view is None:
            print(f"  ⚠️  Could not find source elevation view for {sheet_num}")
            print(f"     Searched: {cfg['search']}")
            continue

        source_id = source_view.get("id")
        print(f"  📋 Duplicating '{source_view.get('name')}' → '{study_name}'")

        # Duplicate the view
        dup_result = rc.call("revit.duplicate_view", {
            "view_id": source_id,
            "name": study_name,
            "duplicate_type": "WithDetailing",  # keep annotation geometry, we'll hide categories
        })

        if not dup_result.get("success"):
            print(f"  ⚠️  Could not duplicate view: {dup_result.get('error', 'unsupported')}")
            print(f"     Manually: duplicate '{source_view.get('name')}', rename to '{study_name}'")
            continue

        new_view_id = dup_result.get("result", {}).get("view_id")
        print(f"  ✅ Duplicated → view id {new_view_id}")

        # Hide annotation categories in the new view
        hidden = _hide_categories_in_view(new_view_id)
        if hidden:
            print(f"  ✅ Hidden {hidden} annotation categories")
        else:
            print(f"  ⚠️  Category visibility override not supported — hide manually:")
            print(f"     Open '{study_name}' → VG (Visibility/Graphics) → Annotations → uncheck:")
            for cat in ["Door Tags", "Window Tags", "Dimensions", "Callout Heads", "Elevation Tags"]:
                print(f"       • {cat}")

        study_views[sheet_num] = new_view_id

    return study_views


def _find_view(view_map: dict, search_terms: list):
    """Find a view by any of the search terms (case-insensitive partial match)."""
    for name, view in view_map.items():
        for term in search_terms:
            if term.lower() in name.lower():
                return view
    return None


def _hide_categories_in_view(view_id: int) -> int:
    """Hide annotation categories in a view. Returns count hidden."""
    hidden = 0
    for cat in HIDE_CATEGORIES:
        result = rc.call("revit.set_category_visibility", {
            "view_id": view_id,
            "category_name": cat,
            "visible": False,
        })
        if result.get("success"):
            hidden += 1
    return hidden


def _build_study_sheets(sheet_map: dict, view_map: dict,
                         study_elev_views: dict, is_two_story: bool):
    """
    Ensure the study set sheet set exists. Creates any missing sheets.
    Creates a sheet set named 'STUDY SET' containing only study sheets.
    """
    # Define which sheets + which views go on them
    study_sheet_plan = [
        {"number": "A100",    "name": "Cover Sheet"},
        {"number": "A100.1",  "name": "Cover Sheet Interior"},
        {"number": "A100.2.1","name": "3D Views"},
        {"number": "A100.2.2","name": "3D Cuts"},
        {"number": "A101.1",  "name": "Floor Plan F1"},
        {"number": "A105",    "name": "Elevations Sides",      "study_view_key": "A105"},
        {"number": "A106",    "name": "Elevations Front Back",  "study_view_key": "A106"},
    ]
    if is_two_story:
        study_sheet_plan.insert(5, {"number": "A101.2", "name": "Floor Plan F2"})

    for sheet_def in study_sheet_plan:
        num  = sheet_def["number"]
        name = sheet_def["name"]
        view_key = sheet_def.get("study_view_key")

        if num in sheet_map:
            print(f"  ✅ Sheet {num} exists")
            # If this is an elevation sheet, swap viewport to study view
            if view_key and view_key in study_elev_views:
                _swap_viewport(sheet_map[num], study_elev_views[view_key])
        else:
            print(f"  ➕ Creating sheet {num} — {name}")
            result = rc.call("revit.create_sheet", {
                "sheet_number": num,
                "sheet_name":   name,
                "title_block_family": "Barnhaus Title Block",
            })
            if result.get("success"):
                new_sheet_id = result.get("result", {}).get("sheet_id")
                print(f"     ✅ Created (id: {new_sheet_id})")
                # Place view if we have a study view for it
                if view_key and view_key in study_elev_views:
                    _place_view_on_sheet(new_sheet_id, study_elev_views[view_key])
            else:
                print(f"     ⚠️  Could not create: {result.get('error')}")

    # Create the named sheet set
    _create_sheet_set(study_sheet_plan)


def _swap_viewport(sheet: dict, new_view_id: int):
    """Replace the existing viewport on a sheet with the study view."""
    sheet_id = sheet.get("id")
    if not sheet_id or not new_view_id:
        return
    # Remove existing viewport, place new one
    rc.call("revit.remove_viewports_from_sheet", {"sheet_id": sheet_id})
    _place_view_on_sheet(sheet_id, new_view_id)


def _place_view_on_sheet(sheet_id: int, view_id: int):
    result = rc.call("revit.place_viewport_on_sheet", {
        "sheet_id": sheet_id,
        "view_id":  view_id,
        "location": {"x": 1.0, "y": 1.0},
    })
    if result.get("success"):
        print(f"     ✅ Placed view {view_id} on sheet {sheet_id}")
    else:
        print(f"     ⚠️  Could not place view: {result.get('error')}")


def _create_sheet_set(study_sheets: list):
    """Create a named sheet set in Revit called 'STUDY SET'."""
    sheet_numbers = [s["number"] for s in study_sheets] + ["A111"]
    result = rc.call("revit.create_sheet_set", {
        "name": "STUDY SET",
        "sheet_numbers": sheet_numbers,
    })
    if result.get("success"):
        print(f"  ✅ Sheet set 'STUDY SET' created/updated")
    else:
        print(f"  ⚠️  Sheet set creation not supported — create manually:")
        print(f"     File → Print → Sheet/View → Manage → New → 'STUDY SET'")
        print(f"     Include: {', '.join(sheet_numbers)}")


def _handle_a111(doc_title: str, sheet_map: dict) -> str | None:
    """Generate A111 upsell page PDF. Returns path or None."""
    full_sheet_count = len(sheet_map)
    output_path = f"/mnt/c/Users/mitch/Documents/{doc_title.replace(' ', '_')}_A111.pdf"
    try:
        generate_a111(
            project_name=doc_title,
            full_sheet_count=full_sheet_count,
            output_path=output_path,
        )
        print(f"  ✅ A111 generated: {output_path}")
        return output_path
    except Exception as e:
        print(f"  ⚠️  A111 generation failed: {e}")
        return None


def _export_revit_pdf(doc_title: str) -> str | None:
    """Export study set sheets to PDF via bridge."""
    output_path = f"/mnt/c/Users/mitch/Documents/{doc_title.replace(' ', '_')}_Study_Set_Revit.pdf"
    result = rc.call("revit.export_pdf", {
        "sheet_set_name": "STUDY SET",
        "output_path": output_path,
        "paper_size": "ArchD",
        "color_depth": "Color",
    })
    if result.get("success"):
        print(f"  ✅ Revit PDF exported: {output_path}")
        return output_path
    else:
        print(f"  ⚠️  PDF export not supported via bridge: {result.get('error')}")
        return None


def _merge_pdfs(revit_pdf: str, a111_pdf: str, doc_title: str) -> str:
    """Merge Revit export + A111 into final study set PDF."""
    from pypdf import PdfWriter, PdfReader

    output_path = f"/mnt/c/Users/mitch/Documents/{doc_title.replace(' ', '_')}_Study_Set.pdf"
    writer = PdfWriter()

    for path in [revit_pdf, a111_pdf]:
        if path and os.path.exists(path):
            reader = PdfReader(path)
            for page in reader.pages:
                writer.add_page(page)

    with open(output_path, "wb") as f:
        writer.write(f)

    print(f"  ✅ Merged PDF: {output_path}")
    return output_path


def _save_export_state(doc_title: str, a111_path: str):
    state = {"doc_title": doc_title, "a111_path": a111_path}
    with open("study_set_state.json", "w") as f:
        json.dump(state, f)


def _load_export_state() -> dict:
    if os.path.exists("study_set_state.json"):
        with open("study_set_state.json") as f:
            return json.load(f)
    return {}
